version: "3.8"

services:
  web:
    container_name: client
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm start
    working_dir: /app

  api:
    build: ./server
    ports:
      - 4000:4000
    environment:
      DB_URL: mongodb://db:27017/matchiq
      VAULT_ADDR: http://vault:8200
    volumes:
      - ./server:/app
    depends_on:
      - db

  db:
    image: mongo:4.0-xenial
    container_name: mongodb
    restart: always
    ports:
      - 27018:27017
    environment:
      VAULT_ADDR: http://vault:8200
    volumes:
      - matchiq:/data/db
  
  django:
    container_name: django
    build: ./django_be
    ports:
      - 8000:8000
    restart: always
    environment:
      DB_URL: mongodb://db:27017/matchiq
      VAULT_ADDR: http://vault:8200
    depends_on:
      - db
    volumes:
      - ./django_be:/app

  vault:
      image: hashicorp/vault
      container_name: vault
      ports:
        - 8200:8200
      environment:
        VAULT_DEV_ROOT_TOKEN_ID: "ABLMW"
        VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
        VAULT_ADDR: "http://0.0.0.0:8200"
      cap_add:
        - IPC_LOCK
      restart: always
      command: "vault server -dev"

volumes:
  matchiq:
