POST http://localhost:4000/api/users
Content-Type: application/json

{
    "userName": "Test 35",
    "password": "password1"
}

###

GET http://localhost:4000/api/users/loggedInData
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWQ0MGRiMDUyYjEyYmEzZjM0MGZjNGIiLCJpYXQiOjE3MDkwODczNjUsImV4cCI6MTcwOTA4NzM4MH0.Q8TXYsuqQ92RVVWjeLXfs207oeSlE9iSvHapuCSFO1A

###

GET http://localhost:5000/api/auth/loggedInData
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWQ0MGRiMDUyYjEyYmEzZjM0MGZjNGIiLCJpYXQiOjE3MDkwODczNjUsImV4cCI6MTcwOTA4NzM4MH0.Q8TXYsuqQ92RVVWjeLXfs207oeSlE9iSvHapuCSFO1A


###

POST http://localhost:5000/api/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWQ0MGRiMDUyYjEyYmEzZjM0MGZjNGIiLCJpYXQiOjE3MDk2ODkyNDYsImV4cCI6MTcwOTY4OTI3Nn0.YDIZMwG00XpQH29Qn45lArd0eZBKzA7lvlOo-3_4khI"

}
###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "userName": "Test 35",
    "password": "password1"
}

###

DELETE http://localhost:4000/api/users/65cf0b5625612a1ea04ceb8c
Content-Type: application/json

### Auth Endpoints

POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "userName": "NewUser",
    "password": "newpassword",
    "email": "newuser@example.com",
    "premiumUser": false
}

###

POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "userName": "NewUser",
    "password": "newpassword"
}

###

POST http://localhost:4000/api/auth/logout
Cookie: refreshToken=your_refresh_token_here

###

POST http://localhost:4000/api/auth/validate
Cookie: accessToken=your_access_token_here

###

POST http://localhost:4000/api/auth/change_password
Authorization: Bearer your_access_token_here
Content-Type: application/json

{
    "userId": "your_user_id_here",
    "currentPassword": "newpassword",
    "newPassword": "newpassword2"
}

###

### Jobs Endpoints

GET http://localhost:4000/api/jobs

###

GET http://localhost:4000/api/jobs/locations

###

GET http://localhost:4000/api/jobs/your_job_id_here

###

POST http://localhost:4000/api/jobs
Content-Type: application/json

{
    "title": "Software Engineer",
    "description": "Develop and maintain software applications.",
    "location": "San Francisco",
    "skills": ["JavaScript", "Node.js"]
}

