POST https://matchiq-api-8d1eb08929d0.herokuapp.com/api/users
Content-Type: application/json

{
    "userName": "Test 35",
    "password": "password1"
}

###

GET https://matchiq-api-8d1eb08929d0.herokuapp.com/api/users/loggedInData
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWQ0MGRiMDUyYjEyYmEzZjM0MGZjNGIiLCJpYXQiOjE3MDkwODczNjUsImV4cCI6MTcwOTA4NzM4MH0.Q8TXYsuqQ92RVVWjeLXfs207oeSlE9iSvHapuCSFO1A

###

GET http://localhost:5000/api/auth/loggedInData
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWQ0MGRiMDUyYjEyYmEzZjM0MGZjNGIiLCJpYXQiOjE3MDkwODczNjUsImV4cCI6MTcwOTA4NzM4MH0.Q8TXYsuqQ92RVVWjeLXfs207oeSlE9iSvHapuCSFO1A


###

POST http://localhost:5000/api/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWQ0MGRiMDUyYjEyYmEzZjM0MGZjNGIiLCJpYXQiOjE3MDk2ODkyNDYsImV4cCI6MTcwOTY4OTI3Nn0.YDIZMwG00XpQH29Qn45lArd0eZBKzA7lvlOo-3_4khI"

}
###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "userName": "Test 35",
    "password": "password1"
}

###

DELETE https://matchiq-api-8d1eb08929d0.herokuapp.com/api/users/65cf0b5625612a1ea04ceb8c
Content-Type: application/json


